name = "portfolio"
compatibility_date = "2024-12-04"
account_id = "542df35b96adc815bb206346b0353c5a"

main = ".vercel/output/static/_worker.js/index.js"

[env.production]
name = "portfolio"

[env.preview]
name = "portfolio-preview"